In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import scipy.sparse
import lightgbm as lgb
%matplotlib inline
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score
from sklearn.metrics import mean_squared_error
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder
from tqdm import tqdm_notebook
from itertools import product
import gc

/anaconda3/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
/anaconda3/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
/anaconda3/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
/anaconda3/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
/anaconda3/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
/anaconda3/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
/anaconda3/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)

In [2]:
def downcast_dtype(df):
    float64_cols = [c for c in df if df[c].dtype == 'float64']
    int64_cols = [c for c in df if df[c].dtype == 'int64']
    df[float64_cols] = df[float64_cols].astype(np.float32)
    df[int64_cols] = df[int64_cols].astype(np.int32)
    return df

In [3]:
sales = pd.read_csv('./all/sales_train.csv.gz')
shops = pd.read_csv('./all/shops.csv')
items = pd.read_csv('./all/items.csv')
item_cats = pd.read_csv('./all/item_categories.csv')
tests = pd.read_csv('./all/test.csv.gz')
sample_submission = pd.read_csv("./all/sample_submission.csv.gz")

In [4]:
tests['date_block_num'] = 34
all_data_test = tests

In [5]:
# Category grouped
l_cat = list(item_cats.item_category_name)

for ind in range(0,1):

    l_cat[ind] = 'PC Headsets / Headphones'

for ind in range(1,8):

    l_cat[ind] = 'Access'

l_cat[8] = 'Tickets (figure)'

l_cat[9] = 'Delivery of goods'

for ind in range(10,18):

    l_cat[ind] = 'Consoles'

for ind in range(18,25):

    l_cat[ind] = 'Consoles Games'

l_cat[25] = 'Accessories for games'

for ind in range(26,28):

    l_cat[ind] = 'phone games'

for ind in range(28,32):

    l_cat[ind] = 'CD games'

for ind in range(32,37):

    l_cat[ind] = 'Card'

for ind in range(37,43):

    l_cat[ind] = 'Movie'

for ind in range(43,55):

    l_cat[ind] = 'Books'

for ind in range(55,61):

    l_cat[ind] = 'Music'

for ind in range(61,73):

    l_cat[ind] = 'Gifts'

for ind in range(73,79):

    l_cat[ind] = 'Soft'

for ind in range(79,81):

    l_cat[ind] = 'Office'

for ind in range(81,83):

    l_cat[ind] = 'Clean'

l_cat[83] = 'Elements of a food'

le = LabelEncoder()
item_cats['item_cat_id_fix'] = le.fit_transform(l_cat)

In [6]:
sales.loc[sales.item_cnt_day < 0,'item_cnt_day'] = 0
sales['revenue'] = sales['item_price'] * sales['item_cnt_day']

In [7]:
sales.head()

,date,date_block_num,shop_id,item_id,item_price,item_cnt_day,revenue
0,02.01.2013,0,59,22154,999.00,1.0,999.00
1,03.01.2013,0,25,2552,899.00,1.0,899.00
2,05.01.2013,0,25,2552,899.00,0.0,0.00
3,06.01.2013,0,25,2554,1709.05,1.0,1709.05
4,15.01.2013,0,25,2555,1099.00,1.0,1099.00

In [8]:
#  init all_data
index_cols = ['shop_id','item_id','date_block_num']
grid = []
for block_num in sales['date_block_num'].unique():
    cur_shops = sales.loc[sales['date_block_num'] == block_num,'shop_id'].unique()
    cur_items = sales.loc[sales['date_block_num'] == block_num,'item_id'].unique()
    grid.append(np.array(list(product(*[cur_shops,cur_items,[block_num]])),dtype = 'int32'))
grid = pd.DataFrame(np.vstack(grid),columns = index_cols,dtype = np.int32)
# groupby data ro get shop_item_month aggregates
gb = sales.groupby(index_cols,as_index = False).agg({'item_cnt_day' : { 'target':'sum'},'revenue': {'total_revenue':'sum'}})
gb.columns = [col[0] if col[-1] == '' else col[-1] for col in gb.columns.values]
all_data = pd.merge(grid,gb,on = index_cols,how = 'left').fillna(0)
all_data_test = pd.merge(all_data_test,gb,on = index_cols,how = 'left').fillna(0)

# group by data get shop_month aggregates
gb = sales.groupby(['shop_id','date_block_num'],as_index = False).agg({'item_cnt_day': { 'target_shop': 'sum'} ,'revenue': {'total_revenue_shop':'sum'} })
gb.columns = [col[0] if col[-1] == '' else col[-1] for col in gb.columns.values]

all_data = pd.merge(all_data,gb,how = 'left',on = ['shop_id','date_block_num']).fillna(0)
all_data_test = pd.merge(all_data_test,gb,on = ['shop_id','date_block_num'],how = 'left').fillna(0)

# group by data get item_month aggregates
gb = sales.groupby(['item_id','date_block_num'],as_index = False).agg({'item_cnt_day': {'target_item': 'sum'} ,'revenue': {'total_revenue_item':'sum'}})
gb.columns = [col[0] if col[-1] == '' else col[-1] for col in gb.columns.values]

all_data = pd.merge(all_data,gb,how = 'left',on = ['item_id','date_block_num']).fillna(0)
all_data_test = pd.merge(all_data_test,gb,on = ['item_id','date_block_num'],how = 'left').fillna(0)

all_data = downcast_dtype(all_data)
all_data_test = downcast_dtype(all_data_test)
del grid,gb

gc.collect()

/anaconda3/lib/python3.6/site-packages/pandas/core/groupby/groupby.py:4658: FutureWarning: using a dict with renaming is deprecated and will be removed in a future version
  return super(DataFrameGroupBy, self).aggregate(arg, *args, **kwargs)

140

In [9]:
# Mean item_cnt_month features
# group = all_data.groupby(['date_block_num']).agg({'target':['mean']})
# group.columns = ['date_avg_cnt']
# group.reset_index(inplace = True)
# all_data = pd.merge(all_data,group,on = ['date_block_num'],how = 'left').fillna(0)
# all_data_test = pd.merge(all_data_test,group,on = ['date_block_num'],how = 'left').fillna(0)

group = all_data.groupby(['item_id','date_block_num']).agg({'target':['mean']})
group.columns = ['date_item_avg_cnt']
group.reset_index(inplace=True)
all_data = pd.merge(all_data,group,on = ['item_id','date_block_num'],how = 'left').fillna(0)
all_data_test = pd.merge(all_data_test,group,on = ['item_id','date_block_num'],how = 'left').fillna(0)

# group = all_data.groupby(['shop_id']).agg({'target':['mean']})
# group.columns = ['date_shop_avg_cnt']
# group.reset_index(inplace=True)
# all_data = pd.merge(all_data,group,on = ['shop_id'],how = 'left').fillna(0)
# all_data_test = pd.merge(all_data_test,group,on = ['shop_id'],how = 'left').fillna(0)

In [10]:
# average revenue
group = sales.groupby(['date_block_num','shop_id']).agg({'revenue':['sum']})
group.columns = ['date_shop_revenue']
group.reset_index(inplace = True)

group = group.groupby(['shop_id']).agg({'date_shop_revenue':['mean']})
group.columns = ['shop_avg_revenue']
group.reset_index(inplace = True)

all_data = all_data.merge(group,on = 'shop_id',how = 'left')
all_data['delta_revenue'] = (all_data['total_revenue_shop'] - all_data['shop_avg_revenue']) / all_data['shop_avg_revenue']
all_data_test = all_data_test.merge(group,on = 'shop_id',how = 'left')
all_data_test['delta_revenue'] = (all_data_test['total_revenue_shop'] - all_data_test['shop_avg_revenue']) / all_data_test['shop_avg_revenue']

In [11]:
# Trend item_price
# group = sales.groupby('item_id').agg({'item_price': 'mean'})
# group.columns = ['item_avg_item_price']
# group.reset_index(inplace = True)
# all_data = pd.merge(all_data,group,on = 'item_id',how = 'left')
# all_data_test = pd.merge(all_data_test,group,on = 'item_id',how = 'left')

# group = sales.groupby(['item_id','date_block_num']).agg({'item_price': 'mean'})
# group.columns = ['date_item_avg_item_price']
# group.reset_index(inplace = True)

# all_data = pd.merge(all_data,group,on = ['item_id','date_block_num'],how = 'left')
# all_data_test = pd.merge(all_data_test,group,on = ['item_id','date_block_num'],how = 'left')

In [12]:
cols_to_rename = list(all_data.columns.difference(index_cols))
shift_range = [1,2,3,4,5,12]
for month_shift in tqdm_notebook(shift_range):
    train_shift = all_data[index_cols + cols_to_rename].copy()
    train_shift['date_block_num']  = train_shift['date_block_num']  + month_shift
    foo = lambda x: '{}_lag_{}'.format(x,month_shift) if x in cols_to_rename else x
    train_shift = train_shift.rename(columns = foo)
    all_data = pd.merge(all_data,train_shift,on = index_cols,how = 'left').fillna(0)
    all_data_test = pd.merge(all_data_test,train_shift,on = index_cols,how = 'left').fillna(0)
del train_shift

HBox(children=(IntProgress(value=0, max=6), HTML(value='')))

In [13]:
cols_to_rename

['date_item_avg_cnt',
 'delta_revenue',
 'shop_avg_revenue',
 'target',
 'target_item',
 'target_shop',
 'total_revenue',
 'total_revenue_item',
 'total_revenue_shop']

In [14]:
item_category_mapping = items[['item_id','item_category_id']].drop_duplicates()
le = LabelEncoder()
le.fit(items['item_category_id'])
item_category_mapping['item_category_id'] = le.transform(items['item_category_id'])

all_data = pd.merge(all_data, item_category_mapping, how='left', on='item_id')
all_data = pd.merge(all_data,item_cats[['item_cat_id_fix', 'item_category_id']],how = 'left',on = 'item_category_id')

all_data = downcast_dtype(all_data)

all_data_test = pd.merge(all_data_test, item_category_mapping, how='left', on='item_id')
all_data_test = pd.merge(all_data_test,item_cats[['item_cat_id_fix', 'item_category_id']],how = 'left',on = 'item_category_id')
all_data_test = downcast_dtype(all_data_test)
gc.collect();

In [15]:
# Mean Encoding
def add_noise(series, noise_level):
    return series * (1 + noise_level * np.random.randn(len(series)))

def target_encode(trn_series=None, 
                  tst_series=None, 
                  target=None, 
                  min_samples_leaf=1, 
                  smoothing=1,
                  noise_level=0):
    """
    Smoothing is computed like in the following paper by Daniele Micci-Barreca
    https://kaggle2.blob.core.windows.net/forum-message-attachments/225952/7441/high%20cardinality%20categoricals.pdf
    trn_series : training categorical feature as a pd.Series
    tst_series : test categorical feature as a pd.Series
    target : target data as a pd.Series
    min_samples_leaf (int) : minimum samples to take category average into account
    smoothing (int) : smoothing effect to balance categorical average vs prior  
    """ 
    assert len(trn_series) == len(target)
    assert trn_series.name == tst_series.name
    temp = pd.concat([trn_series, target], axis=1)
    # Compute target mean 
    averages = temp.groupby(by=trn_series.name)[target.name].agg(["mean", "count"])
    # Compute smoothing
    smoothing = 1 / (1 + np.exp(-(averages["count"] - min_samples_leaf) / smoothing))
    # Apply average function to all target data
    prior = target.mean()
    # The bigger the count the less full_avg is taken into account
    averages[target.name] = prior * (1 - smoothing) + averages["mean"] * smoothing
    averages.drop(["mean", "count"], axis=1, inplace=True)
    # Apply averages to trn and tst series
    print(averages)
    print(averages.reset_index().rename(columns={'index': target.name, target.name: 'average'}))
    ft_trn_series = pd.merge(
        trn_series.to_frame(trn_series.name),
        averages.reset_index().rename(columns={'index': target.name, target.name: 'average'}),
        on=trn_series.name,
        how='left')['average'].rename(trn_series.name + '_mean').fillna(prior)
    # pd.merge does not keep the index so restore it
    ft_trn_series.index = trn_series.index
    
#     corr = np.corrcoef(target.values, encoded_feature)[0][1]
    ft_tst_series = pd.merge(
        tst_series.to_frame(tst_series.name),
        averages.reset_index().rename(columns={'index': target.name, target.name: 'average'}),
        on=tst_series.name,
        how='left')['average'].rename(trn_series.name + '_mean').fillna(prior)
    # pd.merge does not keep the index so restore it
    ft_tst_series.index = tst_series.index
    return add_noise(ft_trn_series, noise_level), add_noise(ft_tst_series, noise_level)

In [16]:
# def target_encode(train_series=None,
#                   test_series=None,
#                   target=None,
#                   noise_level=0):
#     assert len(train_series) == len(target)
#     assert train_series.name == test_series.name

#     temp = pd.concat([train_series, target], axis=1)
#     # Compute target mean
#     aggregated_values = temp.groupby(by=train_series.name)[target.name].agg(["mean", "count", np.std])
#     total_std = np.std(target)
#     aggregated_values["std"].fillna(total_std, inplace=True)

#     # Compute smoothing
#     smoothing_component = aggregated_values["count"] * total_std ** 2
#     smoothing = smoothing_component / (aggregated_values["std"] ** 2 + smoothing_component)

#     # Apply average function to all target data
#     mean_total = target.mean()
#     mean_values = mean_total * (1 - smoothing) + aggregated_values["mean"] * smoothing

#     mean_values_dict = mean_values.rank(axis=0, method='first').to_dict()

#     train_columns = train_series.replace(mean_values_dict).fillna(mean_total)
#     test_columns = test_series.replace(mean_values_dict).fillna(mean_total)
    
#     return add_noise(train_columns, noise_level), add_noise(test_columns, noise_level)

In [17]:
# # mean target encoding 
mean_target_cols = ['item_id','shop_id','item_category_id','item_cat_id_fix']
# mean_target_cols = ['item_category_id','item_cat_id_fix']
for col in mean_target_cols:
    train_enc,test_enc = target_encode(all_data[col],all_data_test[col],all_data['target'])
    all_data = pd.concat([all_data,train_enc],axis = 1)
    all_data_test = pd.concat([all_data_test,test_enc],axis = 1)

           target
item_id
0        0.020000
1        0.023810
2        0.019802
3        0.019802
4        0.020000
5        0.020000
6        0.020000
7        0.020000
8        0.019802
9        0.019608
10       0.020000
11       0.020000
12       0.021739
13       0.020000
14       0.020000
15       0.020000
16       0.020000
17       0.020000
18       0.019608
19       0.022222
20       0.019608
21       0.020000
22       0.021277
23       0.021277
24       0.021277
25       0.019608
26       0.019231
27       0.056834
28       0.142857
29       0.040498
...           ...
22140    0.193462
22141    0.276042
22142    0.069930
22143    1.930804
22144    0.268966
22145    0.654472
22146    0.040334
22147    0.083445
22148    0.021739
22149    0.058923
22150    0.088821
22151    1.159375
22152    0.155109
22153    0.026627
22154    0.109870
22155    0.094937
22156    0.029197
22157    0.021978
22158    0.022727
22159    0.172414
22160    0.097030
22161    0.022222
22162    1.559020
22163    0.581395
22164    1.238095
22165    0.021277
22166    0.295918
22167    1.081900
22168    0.032967
22169    0.020833

[21807 rows x 1 columns]
       item_id   average
0            0  0.020000
1            1  0.023810
2            2  0.019802
3            3  0.019802
4            4  0.020000
5            5  0.020000
6            6  0.020000
7            7  0.020000
8            8  0.019802
9            9  0.019608
10          10  0.020000
11          11  0.020000
12          12  0.021739
13          13  0.020000
14          14  0.020000
15          15  0.020000
16          16  0.020000
17          17  0.020000
18          18  0.019608
19          19  0.022222
20          20  0.019608
21          21  0.020000
22          22  0.021277
23          23  0.021277
24          24  0.021277
25          25  0.019608
26          26  0.019231
27          27  0.056834
28          28  0.142857
29          29  0.040498
...        ...       ...
21777    22140  0.193462
21778    22141  0.276042
21779    22142  0.069930
21780    22143  1.930804
21781    22144  0.268966
21782    22145  0.654472
21783    22146  0.040334
21784    22147  0.083445
21785    22148  0.021739
21786    22149  0.058923
21787    22150  0.088821
21788    22151  1.159375
21789    22152  0.155109
21790    22153  0.026627
21791    22154  0.109870
21792    22155  0.094937
21793    22156  0.029197
21794    22157  0.021978
21795    22158  0.022727
21796    22159  0.172414
21797    22160  0.097030
21798    22161  0.022222
21799    22162  1.559020
21800    22163  0.581395
21801    22164  1.238095
21802    22165  0.021277
21803    22166  0.295918
21804    22167  1.081900
21805    22168  0.032967
21806    22169  0.020833

[21807 rows x 2 columns]
           target
shop_id
0        0.718848
1        0.387582
2        0.131272
3        0.121734
4        0.188400
5        0.189759
6        0.430747
7        0.287112
8        0.110052
9        0.628375
10       0.107624
11       0.094499
12       0.316316
13       0.128831
14       0.198853
15       0.304948
16       0.264082
17       0.180231
18       0.280537
19       0.314939
20       0.499957
21       0.293636
22       0.257935
23       0.235930
24       0.273560
25       1.035590
26       0.290810
27       0.612446
28       0.789942
29       0.283322
30       0.319317
31       1.330543
32       0.152109
33       0.099270
34       0.069274
35       0.295603
36       0.061519
37       0.198408
38       0.231066
39       0.137903
40       0.069095
41       0.211233
42       0.620725
43       0.274908
44       0.192829
45       0.179559
46       0.338127
47       0.289994
48       0.220006
49       0.119034
50       0.326486
51       0.213423
52       0.213273
53       0.264292
54       0.919327
55       0.315088
56       0.334639
57       0.649840
58       0.376365
59       0.210041
    shop_id   average
0         0  0.718848
1         1  0.387582
2         2  0.131272
3         3  0.121734
4         4  0.188400
5         5  0.189759
6         6  0.430747
7         7  0.287112
8         8  0.110052
9         9  0.628375
10       10  0.107624
11       11  0.094499
12       12  0.316316
13       13  0.128831
14       14  0.198853
15       15  0.304948
16       16  0.264082
17       17  0.180231
18       18  0.280537
19       19  0.314939
20       20  0.499957
21       21  0.293636
22       22  0.257935
23       23  0.235930
24       24  0.273560
25       25  1.035590
26       26  0.290810
27       27  0.612446
28       28  0.789942
29       29  0.283322
30       30  0.319317
31       31  1.330543
32       32  0.152109
33       33  0.099270
34       34  0.069274
35       35  0.295603
36       36  0.061519
37       37  0.198408
38       38  0.231066
39       39  0.137903
40       40  0.069095
41       41  0.211233
42       42  0.620725
43       43  0.274908
44       44  0.192829
45       45  0.179559
46       46  0.338127
47       47  0.289994
48       48  0.220006
49       49  0.119034
50       50  0.326486
51       51  0.213423
52       52  0.213273
53       53  0.264292
54       54  0.919327
55       55  0.315088
56       56  0.334639
57       57  0.649840
58       58  0.376365
59       59  0.210041
                     target
item_category_id
0                  0.021898
1                  0.021978
2                  0.429322
3                  1.374776
4                  0.323400
5                  0.285342
6                  0.659155
7                  0.462780
8                  6.163596
9                  1.930763
10                 0.021739
11                 0.349223
12                 3.151033
13                 0.188503
14                 0.272006
15                 0.326365
16                 0.564001
17                 0.080322
18                 0.029810
19                 0.760148
20                 1.917385
21                 0.493207
22                 0.422545
23                 0.668371
24                 0.403573
25                 0.243423
26                 0.110572
27                 0.021053
28                 1.287298
29                 1.078209
...                     ...
54                 0.168209
55                 0.224454
56                 0.083317
57                 0.106268
58                 0.045965
59                 0.069161
60                 0.065770
61                 0.136102
62                 0.189213
63                 0.328289
64                 0.311461
65                 0.753468
66                 0.138270
67                 0.170614
68                 0.032502
69                 0.279352
70                 0.433908
71                94.008003
72                 0.226343
73                 0.458322
74                 0.059656
75                 0.422316
76                 0.082803
77                 0.113671
78                 0.032951
79                 9.981085
80                 3.903944
81                 0.375000
82                 2.540652
83                 1.649596

[84 rows x 1 columns]
    item_category_id    average
0                  0   0.021898
1                  1   0.021978
2                  2   0.429322
3                  3   1.374776
4                  4   0.323400
5                  5   0.285342
6                  6   0.659155
7                  7   0.462780
8                  8   6.163596
9                  9   1.930763
10                10   0.021739
11                11   0.349223
12                12   3.151033
13                13   0.188503
14                14   0.272006
15                15   0.326365
16                16   0.564001
17                17   0.080322
18                18   0.029810
19                19   0.760148
20                20   1.917385
21                21   0.493207
22                22   0.422545
23                23   0.668371
24                24   0.403573
25                25   0.243423
26                26   0.110572
27                27   0.021053
28                28   1.287298
29                29   1.078209
..               ...        ...
54                54   0.168209
55                55   0.224454
56                56   0.083317
57                57   0.106268
58                58   0.045965
59                59   0.069161
60                60   0.065770
61                61   0.136102
62                62   0.189213
63                63   0.328289
64                64   0.311461
65                65   0.753468
66                66   0.138270
67                67   0.170614
68                68   0.032502
69                69   0.279352
70                70   0.433908
71                71  94.008003
72                72   0.226343
73                73   0.458322
74                74   0.059656
75                75   0.422316
76                76   0.082803
77                77   0.113671
78                78   0.032951
79                79   9.981085
80                80   3.903944
81                81   0.375000
82                82   2.540652
83                83   1.649596

[84 rows x 2 columns]

                   target
item_cat_id_fix
0                0.592781
1                0.243423
2                0.127329
3                0.741214
4                2.017930
5                1.706014
6                0.510869
7                0.760483
8                1.930763
9                1.649596
10               0.408885
11               0.224940
12               0.173059
13               6.955985
14               0.021898
15               0.229550
16               6.163596
17               0.086464
    item_cat_id_fix   average
0                 0  0.592781
1                 1  0.243423
2                 2  0.127329
3                 3  0.741214
4                 4  2.017930
5                 5  1.706014
6                 6  0.510869
7                 7  0.760483
8                 8  1.930763
9                 9  1.649596
10               10  0.408885
11               11  0.224940
12               12  0.173059
13               13  6.955985
14               14  0.021898
15               15  0.229550
16               16  6.163596
17               17  0.086464

In [18]:
#  list of all lagged features
scaler_cols = [col for col in all_data.columns if col[-1] in [str(item) for item in shift_range]]
fit_cols = scaler_cols + mean_target_cols + [col + '_mean' for col in mean_target_cols]
to_drop_cols = (list(set(all_data.columns) - (set(fit_cols) | set(index_cols))) + ['date_block_num'])

In [19]:
to_drop_cols

['target_item',
 'total_revenue_shop',
 'total_revenue_item',
 'total_revenue',
 'delta_revenue',
 'target_shop',
 'date_item_avg_cnt',
 'target',
 'shop_avg_revenue',
 'date_block_num']

In [20]:
# Normallize and Category encoding target encoding 
scaler = StandardScaler()
scaler.fit(all_data[scaler_cols])
all_data[scaler_cols] = scaler.transform(all_data[scaler_cols])
all_data_test[scaler_cols] = scaler.transform(all_data_test[scaler_cols])

In [21]:
all_data.head()

,shop_id,item_id,date_block_num,target,total_revenue,target_shop,total_revenue_shop,target_item,total_revenue_item,date_item_avg_cnt,...,target_shop_lag_12,total_revenue_lag_12,total_revenue_item_lag_12,total_revenue_shop_lag_12,item_category_id,item_cat_id_fix,item_id_mean,shop_id_mean,item_category_id_mean,item_cat_id_fix_mean
0,59,22154,0,1.0,999.0,2026.0,1645059.0,18.0,17982.000000,0.400000,...,-0.45619,-0.030315,-0.041424,-0.459653,37,11,0.109870,0.210041,0.178043,0.224940
1,59,2552,0,0.0,0.0,2026.0,1645059.0,1.0,899.000000,0.022222,...,-0.45619,-0.030315,-0.041424,-0.459653,58,12,0.025455,0.210041,0.045965,0.173059
2,59,2554,0,0.0,0.0,2026.0,1645059.0,1.0,1709.050049,0.022222,...,-0.45619,-0.030315,-0.041424,-0.459653,58,12,0.022222,0.210041,0.045965,0.173059
3,59,2555,0,0.0,0.0,2026.0,1645059.0,2.0,2197.699951,0.044444,...,-0.45619,-0.030315,-0.041424,-0.459653,56,12,0.066429,0.210041,0.083317,0.173059
4,59,2564,0,0.0,0.0,2026.0,1645059.0,5.0,1638.000000,0.111111,...,-0.45619,-0.030315,-0.041424,-0.459653,59,12,0.058524,0.210041,0.069161,0.173059

In [22]:
# Don't use old data from year 2013
all_data = all_data[all_data['date_block_num'] >= 12]
dates = all_data['date_block_num']
last_block = dates.max()

In [23]:
dates_train = dates[dates < last_block]
dates_test = dates[dates == last_block]
X_train = all_data.loc[dates < last_block].drop(to_drop_cols,axis = 1)
X_test = all_data.loc[dates == last_block].drop(to_drop_cols,axis = 1)
X_result = all_data_test.drop(to_drop_cols + ['ID'],axis = 1)
y_train = all_data.loc[dates < last_block,'target'].values
y_test = all_data.loc[dates == last_block,'target'].values

In [24]:
X_result.head()

,shop_id,item_id,date_item_avg_cnt_lag_1,delta_revenue_lag_1,shop_avg_revenue_lag_1,target_lag_1,target_item_lag_1,target_shop_lag_1,total_revenue_lag_1,total_revenue_item_lag_1,...,target_shop_lag_12,total_revenue_lag_12,total_revenue_item_lag_12,total_revenue_shop_lag_12,item_category_id,item_cat_id_fix,item_id_mean,shop_id_mean,item_category_id_mean,item_cat_id_fix_mean
0,5,5037,0.124929,-0.154106,-0.330974,-0.099690,0.106951,-0.406388,-0.051541,0.125827,...,0.45333,0.535923,1.056858,0.889593,19,7,1.963134,0.189759,0.760148,0.760483
1,5,5320,-0.156125,-0.025926,-1.087141,-0.099690,-0.155097,-0.933549,-0.051541,-0.073566,...,-0.45619,-0.030315,-0.041424,-0.459653,55,12,0.334964,0.189759,0.224454,0.173059
2,5,5233,0.316046,-0.154106,-0.330974,0.215281,0.285144,-0.406388,0.158050,0.194373,...,-0.45619,-0.030315,-0.041424,-0.459653,19,7,1.656863,0.189759,0.760148,0.760483
3,5,5232,0.169897,-0.154106,-0.330974,-0.099690,0.148879,-0.406388,-0.051541,0.110072,...,-0.45619,-0.030315,-0.041424,-0.459653,23,7,1.100775,0.189759,0.668371,0.760483
4,5,5268,-0.156125,-0.025926,-1.087141,-0.099690,-0.155097,-0.933549,-0.051541,-0.073566,...,-0.45619,-0.030315,-0.041424,-0.459653,20,7,0.334964,0.189759,1.917385,0.760483

In [25]:
lr = LinearRegression()
lr.fit(X_train.values,y_train)
pred_lr = lr.predict(X_test.values)
pred_lr_result = lr.predict(X_result.values)
print('Test R-squared for linreg is %f' % np.sqrt(mean_squared_error(y_test,pred_lr.clip(0,20))))

Test R-squared for linreg is 5.205325

In [26]:
#====================================================================================================

In [ ]:
lgb_params = {
    'feature_fraction': 0.75,
               'metric': 'rmse',
               'nthread':1, 
               'min_data_in_leaf': 2**7, 
               'bagging_fraction': 0.75, 
               'learning_rate': 0.03, 
               'objective': 'mse', 
               'bagging_seed': 2**7, 
               'num_leaves': 2**7,
               'bagging_freq':1,
               'verbose':0 
}

model = lgb.train(lgb_params, lgb.Dataset(X_train, label=y_train), 100)
pred_lgb = model.predict(X_test)
pred_lgb_result = model.predict(X_result.values)
print('Test R-squared for LightGBM is %f' % np.sqrt(mean_squared_error(y_test,pred_lgb.clip(0,20))))

X_test_level2 = np.c_[pred_lr,pred_lgb]

X_result_level2 = np.c_[pred_lr_result,pred_lgb_result]

dates_train_level2 = dates_train[dates_train.isin([27,28,29,30,31,32])]



y_train_level2 = y_train[dates_train.isin([27,28,29,30,31,32])]

X_train_level2 = np.zeros([y_train_level2.shape[0],2])





for cur_block_num in [27,28,29,30,31,32]:
    '''
        1. Split `X_train` into parts
           Remember, that corresponding dates are stored in `dates_train` 
        2. Fit linear regression 
        3. Fit LightGBM and put predictions          
        4. Store predictions from 2. and 3. in the right place of `X_train_level2`. 
           You can use `dates_train_level2` for it
           Make sure the order of the meta-features is the same as in `X_test_level2`
    '''      
    
    #  YOUR CODE GOES HERE
    X_train_to = all_data.loc[dates < cur_block_num].drop(to_drop_cols,axis = 1)
    X_test_to =  all_data.loc[dates == cur_block_num].drop(to_drop_cols,axis = 1)
    
    y_train_to = all_data.loc[dates < cur_block_num,'target'].values
    lr.fit(X_train_to.values,y_train_to)
    pred_lr = lr.predict(X_test_to)
    
    model = lgb.train(lgb_params,lgb.Dataset(X_train_to,label = y_train_to),100)
    pred_lgb = model.predict(X_test_to)
    
    X_train_level2[dates_train_level2 == cur_block_num] = np.c_[pred_lr, pred_lgb] 

# Stacking
lr.fit(X_train_level2,y_train_level2)
train_preds = lr.predict(X_train_level2)
test_preds = lr.predict(X_test_level2)
test_preds_result = lr.predict(X_result_level2)
print('Test R-squared for LR is %f' % np.sqrt(mean_squared_error(y_train_level2,train_preds.clip(0,20))))
print('Test R-squared for LightGBM is %f' % np.sqrt(mean_squared_error(y_test,test_preds.clip(0,20))))

release = test_preds_result.clip(0,20)
tests['item_cnt_month'] = release
my_submission = tests[['ID','item_cnt_month']]
my_submission.to_csv('./all/to_win_kaggle_avgcnt.csv',index=False)

Test R-squared for LightGBM is 5.187675